name: Build

on:
  push:
    branches:
      - master

env:
  node_version: "12.x"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-hive/gha-npm-cache@v1
      - name: Install JS dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Commit and push distified version to master
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update distified version'
          file_pattern: 'dist/index.js'
          commit_options: '--allow-empty'
